### ISSUE TITLE
Specified `pytest` version conflicts with `pytest-xdist` dependencies

### ISSUE THREAD

**Issue by jmcph4** [ethereum/py-snappy#16]
## What was wrong?
Version mismatch for `pytest` when installing dependencies in virtual environment as per the build instructions (i.e. using `pip install -e .[dev]` - `pytest-xdist` requires `pytest` 3.6.0 or newer, but `pytest` 3.3.2 is specified in `steup.py`. I believe this is causing remote CI tests to fail:

1. [py37-core](https://circleci.com/gh/ethereum/py-snappy/134)
2. [py36-core](https://circleci.com/gh/ethereum/py-snappy/131)

I also encountered this locally before submitting #15 but remedied it only on my development machine manually by running `pip install 'pytest>=3.6.0'`. As a result, I believe #15 is failing for this same reason.

### Code that produced the error

    $ pip install -e .[dev]

### Full error output 

**Note the fourth last line**

    Obtaining file:///home/jack/dev/contrib/py-snappy
    Collecting bumpversion<1,>=0.5.3 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/ad/34/49c914829066558ebd405a56647d3ee26856282b8b8c4cd2c0c8de40ff8e/bumpversion-0.5.3-py2.py3-none-any.whl
    Collecting pytest-watch<5,>=4.1.0 (from py-snappy==0.1.0a0)
    Requirement already satisfied: wheel in ./venv/lib/python3.7/site-packages (from py-snappy==0.1.0a0) (0.32.3)
    Collecting twine (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/26/7f/92c7083b66bc7ed32940cc0e25ae070c033d384d158617635222e7a08e92/twine-1.12.1-py2.py3-none-any.whl
    Collecting ipython (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/f0/b4/a9ea018c73a84ee6280b2e94a1a6af8d63e45903eac2da0640fa63bca4db/ipython-7.2.0-py3-none-any.whl
    Collecting pytest==3.3.2 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/38/af/8dcf688d192914928393f931b7b550f2530299bbb08018b2f17efa6aab73/pytest-3.3.2-py2.py3-none-any.whl
    Collecting pytest-xdist (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/4f/3a/b270094400d243bb4404b3de601955155a418cd8dbc729ff41602c6dd435/pytest_xdist-1.25.0-py2.py3-none-any.whl
    Collecting tox<3,>=2.9.1 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/1d/4e/20c679f8c5948f7c48591fde33d442e716af66a31a88f5791850a75041eb/tox-2.9.1-py2.py3-none-any.whl
    Collecting hypothesis==3.74.3 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/41/51/150bea0aa6bf779a08975f781aaa156a5b91ca7092b2556358f29dc796e1/hypothesis-3.74.3-py3-none-any.whl
    Collecting python-snappy<1,>=0.5.3 (from py-snappy==0.1.0a0)
    Collecting flake8==3.4.1 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/b2/d3/e80ea2616e3871ae22459c415c63d64b9bd744c92267482670fcdbcea72d/flake8-3.4.1-py2.py3-none-any.whl
    Collecting black==18.9b0 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/2a/34/9938749f260a861cdd8427d63899e08f9a2a041159a26c2615b02828c973/black-18.9b0-py36-none-any.whl
    Collecting mypy==0.630 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/32/8c/a668527fe2ea69f3a03fc4d895e12b6cb2eb1bb62d61cfe8ff4142395d3a/mypy-0.630-py3-none-any.whl
    Collecting Sphinx<2,>=1.6.5 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/ff/d5/3a8727d6f890b1ae45da72a55bf8449e9f2c535a444923b338c3f509f203/Sphinx-1.8.2-py2.py3-none-any.whl
    Collecting sphinx_rtd_theme>=0.1.9 (from py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/ef/0c/e4a462190506bc4bff6ca8cf93da07b2d13e540466d2e8a760352d0c69b0/sphinx_rtd_theme-0.4.2-py2.py3-none-any.whl
    Collecting colorama>=0.3.3 (from pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
    Collecting watchdog>=0.6.0 (from pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
    Collecting docopt>=0.4.0 (from pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
    Collecting readme-renderer>=21.0 (from twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/c3/7e/d1aae793900f36b097cbfcc5e70eef82b5b56423a6c52a36dce51fedd8f0/readme_renderer-24.0-py2.py3-none-any.whl
    Collecting requests-toolbelt>=0.8.0 (from twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
    Requirement already satisfied: setuptools>=0.7.0 in ./venv/lib/python3.7/site-packages (from twine->py-snappy==0.1.0a0) (40.6.3)
    Collecting tqdm>=4.14 (from twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/91/55/8cb23a97301b177e9c8e3226dba45bb454411de2cbd25746763267f226c2/tqdm-4.28.1-py2.py3-none-any.whl
    Collecting pkginfo>=1.4.2 (from twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/a3/fe/f32a48d48f40a7209be9825fba2566cab92364787cf37de2e08300dd6ce7/pkginfo-1.4.2-py2.py3-none-any.whl
    Collecting requests!=2.15,!=2.16,>=2.5.0 (from twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
    Collecting backcall (from ipython->py-snappy==0.1.0a0)
    Collecting jedi>=0.10 (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/c2/bc/54d53f5bc4658380d0eca9055d72be4df45e5bfd91a4bac97da224a92553/jedi-0.13.2-py2.py3-none-any.whl
    Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/d1/e6/adb3be5576f5d27c6faa33f1e9fea8fe5dbd9351db12148de948507e352c/prompt_toolkit-2.0.7-py3-none-any.whl
    Collecting traitlets>=4.2 (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
    Collecting pexpect; sys_platform != "win32" (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
    Collecting pickleshare (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
    Collecting pygments (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
    Collecting decorator (from ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
    Collecting six>=1.10.0 (from pytest==3.3.2->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
    Collecting py>=1.5.0 (from pytest==3.3.2->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
    Collecting pluggy<0.7,>=0.5 (from pytest==3.3.2->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/ba/65/ded3bc40bbf8d887f262f150fbe1ae6637765b5c9534bd55690ed2c0b0f7/pluggy-0.6.0-py3-none-any.whl
    Collecting attrs>=17.2.0 (from pytest==3.3.2->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
    Collecting pytest-forked (from pytest-xdist->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/dd/9d/fb75af584b850a902c9ce5ec96ea5c623978113b8a240ab414e1a435df93/pytest_forked-0.2-py2.py3-none-any.whl
    Collecting execnet>=1.1 (from pytest-xdist->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/f9/76/3343e69a2a1602052f587898934e5fea395d22310d39c07955596597227c/execnet-1.5.0-py2.py3-none-any.whl
    Collecting virtualenv>=1.11.2; python_version != "3.2" (from tox<3,>=2.9.1->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/7c/17/9b7b6cddfd255388b58c61e25b091047f6814183e1d63741c8df8dcd65a2/virtualenv-16.1.0-py2.py3-none-any.whl
    Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8==3.4.1->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
    Collecting pyflakes<1.6.0,>=1.5.0 (from flake8==3.4.1->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/27/49/924098b3b85c286696f37e014475d79471ffc44509613af420645a3c12cb/pyflakes-1.5.0-py2.py3-none-any.whl
    Collecting mccabe<0.7.0,>=0.6.0 (from flake8==3.4.1->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
    Collecting click>=6.5 (from black==18.9b0->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
    Collecting toml>=0.9.4 (from black==18.9b0->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
    Collecting appdirs (from black==18.9b0->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
    Collecting mypy-extensions<0.5.0,>=0.4.0 (from mypy==0.630->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/4d/72/8d54e2b296631b9b14961d583e56e90d9d7fba8a240d5ce7f1113cc5e887/mypy_extensions-0.4.1-py2.py3-none-any.whl
    Collecting typed-ast<1.2.0,>=1.1.0 (from mypy==0.630->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/60/c9/48d88c07d19dd0f8609e4579e2e104ca19aafe23e12b3b41769c897e1948/typed_ast-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
    Collecting Jinja2>=2.3 (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
    Collecting docutils>=0.11 (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
    Collecting babel!=2.0,>=1.3 (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
    Collecting snowballstemmer>=1.1 (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
    Collecting packaging (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/89/d1/92e6df2e503a69df9faab187c684585f0136662c12bb1f36901d426f3fab/packaging-18.0-py2.py3-none-any.whl
    Collecting alabaster<0.8,>=0.7 (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
    Collecting imagesize (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
    Collecting sphinxcontrib-websupport (from Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/52/69/3c2fbdc3702358c5b34ee25e387b24838597ef099761fc9a42c166796e8f/sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl
    Collecting pathtools>=0.1.1 (from watchdog>=0.6.0->pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
    Collecting PyYAML>=3.10 (from watchdog>=0.6.0->pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
    Collecting argh>=0.24.1 (from watchdog>=0.6.0->pytest-watch<5,>=4.1.0->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
    Collecting bleach>=2.1.0 (from readme-renderer>=21.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/d4/0d/4696373c3b714f6022d668fbab619690a42050dbeacede6d10ed97fbd3e2/bleach-3.0.2-py2.py3-none-any.whl
    Collecting idna<2.9,>=2.5 (from requests!=2.15,!=2.16,>=2.5.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.15,!=2.16,>=2.5.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
    Collecting urllib3<1.25,>=1.21.1 (from requests!=2.15,!=2.16,>=2.5.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests!=2.15,!=2.16,>=2.5.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
    Collecting parso>=0.3.0 (from jedi>=0.10->ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/09/51/9c48a46334be50c13d25a3afe55fa05c445699304c5ad32619de953a2305/parso-0.3.1-py2.py3-none-any.whl
    Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
    Collecting ipython-genutils (from traitlets>=4.2->ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
    Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
    Collecting apipkg>=1.4 (from execnet>=1.1->pytest-xdist->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
    Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/e4/c4/adcc2d6f2ac2146cc04e076f14f1006c1de8e1e747fa067668b6573000b8/MarkupSafe-1.1.0-cp37-cp37m-manylinux1_x86_64.whl
    Collecting pytz>=0a (from babel!=2.0,>=1.3->Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
    Collecting pyparsing>=2.0.2 (from packaging->Sphinx<2,>=1.6.5->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
    Collecting webencodings (from bleach>=2.1.0->readme-renderer>=21.0->twine->py-snappy==0.1.0a0)
      Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
    pytest-xdist 1.25.0 has requirement pytest>=3.6.0, but you'll have pytest 3.3.2 which is incompatible.
    Installing collected packages: bumpversion, six, py, pluggy, attrs, pytest, colorama, pathtools, PyYAML, argh, watchdog, docopt, pytest-watch, pygments, webencodings, bleach, docutils, readme-renderer, idna, chardet, urllib3, certifi, requests, requests-toolbelt, tqdm, pkginfo, twine, backcall, parso, jedi, wcwidth, prompt-toolkit, decorator, ipython-genutils, traitlets, ptyprocess, pexpect, pickleshare, ipython, pytest-forked, apipkg, execnet, pytest-xdist, virtualenv, tox, hypothesis, python-snappy, pycodestyle, pyflakes, mccabe, flake8, click, toml, appdirs, black, mypy-extensions, typed-ast, mypy, MarkupSafe, Jinja2, pytz, babel, snowballstemmer, pyparsing, packaging, alabaster, imagesize, sphinxcontrib-websupport, Sphinx, sphinx-rtd-theme, py-snappy
    Running setup.py develop for py-snappy
    Successfully installed Jinja2-2.10 MarkupSafe-1.1.0 PyYAML-3.13 Sphinx-1.8.2 alabaster-0.7.12 apipkg-1.5 appdirs-1.4.3 argh-0.26.2 attrs-18.2.0 babel-2.6.0 backcall-0.1.0 black-18.9b0 bleach-3.0.2 bumpversion-0.5.3 certifi-2018.11.29 chardet-3.0.4 click-7.0 colorama-0.4.1 decorator-4.3.0 docopt-0.6.2 docutils-0.14 execnet-1.5.0 flake8-3.4.1 hypothesis-3.74.3 idna-2.8 imagesize-1.1.0 ipython-7.2.0 ipython-genutils-0.2.0 jedi-0.13.2 mccabe-0.6.1 mypy-0.630 mypy-extensions-0.4.1 packaging-18.0 parso-0.3.1 pathtools-0.1.2 pexpect-4.6.0 pickleshare-0.7.5 pkginfo-1.4.2 pluggy-0.6.0 prompt-toolkit-2.0.7 ptyprocess-0.6.0 py-1.7.0 py-snappy pycodestyle-2.3.1 pyflakes-1.5.0 pygments-2.3.1 pyparsing-2.3.0 pytest-3.3.2 pytest-forked-0.2 pytest-watch-4.2.0 pytest-xdist-1.25.0 python-snappy-0.5.3 pytz-2018.7 readme-renderer-24.0 requests-2.21.0 requests-toolbelt-0.8.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-rtd-theme-0.4.2 sphinxcontrib-websupport-1.1.0 toml-0.10.0 tox-2.9.1 tqdm-4.28.1 traitlets-4.3.2 twine-1.12.1 typed-ast-1.1.1 urllib3-1.24.1 virtualenv-16.1.0 watchdog-0.9.0 wcwidth-0.1.7 webencodings-0.5.1

Then running tests locally:

    $ pytest -n 4 -f --maxfail=1
    Traceback (most recent call last):
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
        plugin = ep.load()
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2345, in load
        self.require(*args, **kwargs)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2368, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (pytest 3.3.2 (/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages), Requirement.parse('pytest>=3.6.0'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/jack/dev/contrib/py-snappy/venv/bin/pytest", line 11, in <module>
        sys.exit(main())
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/config.py", line 50, in main
        config = _prepareconfig(args, plugins)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/config.py", line 160, in _prepareconfig
        pluginmanager=pluginmanager, args=args)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
        firstresult=hook.spec_opts.get('firstresult'),
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/callers.py", line 196, in _multicall
        gen.send(outcome)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
        config = outcome.get_result()
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
        raise ex[1].with_traceback(ex[2])
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
        res = hook_impl.function(*args)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/config.py", line 943, in pytest_cmdline_parse
        self.parse(args)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/config.py", line 1108, in parse
        self._preparse(args, addopts=addopts)
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/_pytest/config.py", line 1071, in _preparse
        self.pluginmanager.load_setuptools_entrypoints('pytest11')
      File "/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages/pluggy/__init__.py", line 402, in load_setuptools_entrypoints
        "Plugin %r could not be loaded: %s!" % (ep.name, e))
    pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 3.3.2 (/home/jack/dev/contrib/py-snappy/venv/lib/python3.7/site-packages), Requirement.parse('pytest>=3.6.0'))!

## How can it be fixed?

By modifying https://github.com/ethereum/py-snappy/blob/649a4856018871d3aaa69ce91977d773bc55860c/setup.py#L10

to become

    "pytest>=3.6.0",

**Comment by pipermerriam** [comment]
@jmcph4 :+1: if you'd like to open a PR for this.

**Comment by jmcph4** [comment]
Closing as fixed in #17
